### ISSUE TITLE
Proposed stat-schema

### ISSUE THREAD

**Issue by jimmydorry** [FrenchDeath/EBF#1]
@MNoya what do you think?

flags:
- [ ] version
- [ ] num players
- [ ] difficulty

game:
- [ ] ending round
- [ ] remaining lives

players: 
- [ ] hero
- [ ] level
- [ ] connection status
- ~~damage dealt~~
- ~~damage avoided~~
- ~~damage received~~
- ~~filtered and ordered item list string (just the higher value items)~~
- ~~ability levels list string (in the format of XX/XX/XX/XX/XX)~~

**Comment by elenberg** [comment]
Are you wanting this information to be available to the players on the end screen?

**Comment by jimmydorry** [comment]
Just documenting some stats that would assist in balancing.

@MNoya wanted some suggestions from someone that has played it a few times and I came up with a few that would be interesting.

**Comment by elenberg** [comment]
All I want is a round counter. Just count how many attempts it took to do a round. If we could get that information, that'd be pretty helpful for balancing.

**Comment by jimmydorry** [comment]
The flags and game variables are all easy. The hero, level, connection status are easy.

The remaining player variables are the tricky ones.

It would be fine to leave them out (especially the items and abilities... as they will be the biggest resource hogs).

**Comment by jimmydorry** [comment]
Just merge it https://github.com/FrenchDeath/EBF/pull/2
